language: go
go: 1.8

notifications:
  email: false

env:
  global:
   - TAGS=()

before_install:
  - TAGS+=(debug)
  - TAGS+=(integration)
  - TAGS+=(prebuild)
  - go version

install:
  - go get github.com/Masterminds/glide
  - go get -u github.com/golang/lint/golint

script:
  - glide install
  - (result="`find . -type d -name vendor -prune -o -type f -name '*.go' -exec golint {} \;`"; if [ ! -z "${result}" ]; then echo "${result}"; exit 1; fi)
  - go vet -tags="`echo ${TAGS[@]}`" $(glide novendor)
  - go generate -tags=prebuild ./...
  - |
    for tag in ${TAGS[@]}; do
      echo "go build -v -tags=${tag} $(glide novendor)"
      go build -v -tags=${tag} $(glide novendor)
    done
  - go build -v
  - sed -i "s/[0-9]\{14\}/unknown/g" buildtime/build_information.go
  - go test -tags=integration -v -race $(glide novendor)

